name: Docker cypress/base
on:
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/base:latest
#      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "PR number is $CYPRESS_PULL_REQUEST_ID"
      - run: echo "PR URL is $CYPRESS_PULL_REQUEST_URL"
      - run: echo "Build URL is $CYPRESS_CI_BUILD_URL"
