name: Docker cypress/included
on:
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/base:included
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
